version: "3.3"

services:
  
  cache:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  test_db:
    image: postgres
    volumes:
        - ./test_database-/var/lib/postgresql/data
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=${PG_USER_TEST}
      - POSTGRES_PASSWORD=${PG_PASS_TEST}
      - POSTGRES_DB=${PG_DB_TEST}

  db:
    image: postgres 
    volumes:
        - ./database-/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}

  back:
    build: ./back
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./back:/core
    depends_on:
      - db
      - cache
      - test_db
    command: uvicorn app:app --host ${BACK_HOST} --port ${BACK_PORT} --reload        
