version: "3.3"

services:
  
  cache:
    image: redis
    restart: always
    ports:
      - "6378:6378"

  db:
    image: postgres 
    volumes:
        - ./database-/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}

  back:
    build: ./back
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./back:/core
    depends_on:
      - db
      - cache
    command: uvicorn app:app --host ${BACK_HOST} --port ${BACK_PORT} --reload        
