FROM python:3.10.6

WORKDIR /core

COPY ./requirements.txt /core/requirements.txt

RUN pip install --no-cache-dir -r /core/requirements.txt

COPY ./back /core/back

CMD ['uvicorn', 'back.app:app', '--host', '0.0.0.0', '--port', '8080']

