"""fixed table relationship

Revision ID: 0e2567e48a7a
Revises: 34b398004d45
Create Date: 2022-10-25 22:22:15.435650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2567e48a7a'
down_revision = '34b398004d45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.add_column('admins', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint('admins_admin_fkey', 'admins', type_='foreignkey')
    op.drop_constraint('admins_company_fkey', 'admins', type_='foreignkey')
    op.create_foreign_key(None, 'admins', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'admins', 'users', ['admin_id'], ['id'])
    op.drop_column('admins', 'admin')
    op.drop_column('admins', 'company')
    op.add_column('invitations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('invitations', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint('invitations_user_fkey', 'invitations', type_='foreignkey')
    op.drop_constraint('invitations_company_fkey', 'invitations', type_='foreignkey')
    op.create_foreign_key(None, 'invitations', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'invitations', 'users', ['user_id'], ['id'])
    op.drop_column('invitations', 'company')
    op.drop_column('invitations', 'user')
    op.add_column('owners', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('owners', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint('owners_owner_fkey', 'owners', type_='foreignkey')
    op.drop_constraint('owners_company_fkey', 'owners', type_='foreignkey')
    op.create_foreign_key(None, 'owners', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'owners', 'companies', ['company_id'], ['id'])
    op.drop_column('owners', 'owner')
    op.drop_column('owners', 'company')
    op.add_column('requests', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint('requests_company_fkey', 'requests', type_='foreignkey')
    op.drop_constraint('requests_user_fkey', 'requests', type_='foreignkey')
    op.create_foreign_key(None, 'requests', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'requests', 'users', ['user_id'], ['id'])
    op.drop_column('requests', 'company')
    op.drop_column('requests', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('requests', sa.Column('company', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.create_foreign_key('requests_user_fkey', 'requests', 'users', ['user'], ['id'])
    op.create_foreign_key('requests_company_fkey', 'requests', 'companies', ['company'], ['id'])
    op.drop_column('requests', 'company_id')
    op.drop_column('requests', 'user_id')
    op.add_column('owners', sa.Column('company', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('owners', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'owners', type_='foreignkey')
    op.drop_constraint(None, 'owners', type_='foreignkey')
    op.create_foreign_key('owners_company_fkey', 'owners', 'companies', ['company'], ['id'])
    op.create_foreign_key('owners_owner_fkey', 'owners', 'users', ['owner'], ['id'])
    op.drop_column('owners', 'company_id')
    op.drop_column('owners', 'user_id')
    op.add_column('invitations', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('invitations', sa.Column('company', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.create_foreign_key('invitations_company_fkey', 'invitations', 'companies', ['company'], ['id'])
    op.create_foreign_key('invitations_user_fkey', 'invitations', 'users', ['user'], ['id'])
    op.drop_column('invitations', 'company_id')
    op.drop_column('invitations', 'user_id')
    op.add_column('admins', sa.Column('company', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('admins', sa.Column('admin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.create_foreign_key('admins_company_fkey', 'admins', 'companies', ['company'], ['id'])
    op.create_foreign_key('admins_admin_fkey', 'admins', 'users', ['admin'], ['id'])
    op.drop_column('admins', 'company_id')
    op.drop_column('admins', 'admin_id')
    # ### end Alembic commands ###
