"""companies

Revision ID: 34b398004d45
Revises: 418e0cac3c47
Create Date: 2022-10-25 19:48:02.160730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b398004d45'
down_revision = '418e0cac3c47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admins', ['id'])
    op.add_column('companies', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'companies', ['id'])
    op.create_foreign_key(None, 'companies', 'users', ['owner'], ['id'])
    op.create_unique_constraint(None, 'invitations', ['id'])
    op.create_unique_constraint(None, 'owners', ['id'])
    op.create_unique_constraint(None, 'requests', ['id'])
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'requests', type_='unique')
    op.drop_constraint(None, 'owners', type_='unique')
    op.drop_constraint(None, 'invitations', type_='unique')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'owner')
    op.drop_constraint(None, 'admins', type_='unique')
    # ### end Alembic commands ###
